### ISSUE TITLE
qbatch error

### ISSUE THREAD

**Issue by neer86upadhyay** [CobraLab/MAGeTbrain#55]
Dear Gabriel,
 we tried to check for the command you said but it doesn't provide any output. We have not done any configuration related with the batch environment. As we are very naive, could you please guid us How we can do that or which commands we need to select among the following:$ export QBATCH_PPJ=12                   # requested processors per job
$ export QBATCH_CHUNKSIZE=$QBATCH_PPJ    # commands to run per job
$ export QBATCH_CORES=$QBATCH_PPJ        # commonds to run in parallel per job
$ export QBATCH_NODES=1                  # number of compute nodes to request for the job, typically for MPI jobs
$ export QBATCH_MEM="0"                  # requested memory per job
$ export QBATCH_MEMVARS="mem"            # memory request variable to set
$ export QBATCH_SYSTEM="pbs"             # queuing system to use ("pbs", "sge","slurm", or "local")
$ export QBATCH_NODES=1                  # (PBS-only) nodes to request per job
$ export QBATCH_SGE_PE="smp"             # (SGE-only) parallel environment name
$ export QBATCH_QUEUE="1day"             # Name of submission queue
$ export QBATCH_OPTIONS=""               # Arbitrary cluster options to embed in all jobs
$ export QBATCH_SCRIPT_FOLDER=".qbatch/" # Location to generate jobfiles for submission
$ export QBATCH_SHELL="/bin/sh"          # Shell to use to evaluate jobfile

Best Regards, 
Neeraj

**Comment by gdevenyi** [comment]
Hi,

You appear to be attempting to install/use MAGeTbrain on a local single-user system, and furthermore don't have the IT support to do it for you. We cannot provide such installation support beyond the instructions already provided. It is up to users to understand their systems as we do not have access to them.

We strongly suggest you consider using our shared resource we provide on a supercomputer (email me if you wish to discuss using our supercomputing resources), otherwise, I suggest looking at https://github.com/CoBrALab/MAGeTDocker which provides a container will everything installed and configured, and a wrapper to use it.
