### ISSUE TITLE
Problem about segment habenula 

### ISSUE THREAD

**Issue by wangyidada** [CobraLab/MAGeTbrain#58]
Dear Gabriel,
We are trying to segment the habenula from the t1 images using the MAGeTBrain. We are getting the following error when ran the mb run. We used t1 images and habenula label files in the atlase dataset, and the template and subject were also the same t1 files in the atlases dataset, but the registration results showed bigger than normal habenula labels. 
We can use Slicer software to open the .mnc files in the atlase dataset, but it can’t open the output labelmask_fine.mnc file. Do you know the reason?
I am looking forward to your response.

**Comment by gdevenyi** [comment]
> We are getting the following error when ran the mb run. 

Segmentations you consider "not correct" are not an error. MAGeTbrain is deterministic in terms of registration, voting, and resampling and if it ran to completetion there is not "error".

>  but it can’t open the output labelmask_fine.mnc file

MINC files are handled by the open source minc-toolkit-v2, available for download here, https://bic-mni.github.io/#v2-version-1918 . The `Display` program can be used to open the images. Otherwise, the mnc2nii/nii2mnc tool can be used for conversion.

> registration results showed bigger than normal habenula labels.

I suggest you check the original atlases and definition from the paper, to ensure our defition and ours are similar, otherwise you may be expecting another size.

Our recommended run configuration is to use preprocessed (bias field corrected) and brain-extracted for all inputs to improve registrations.

**Comment by wangyidada** [comment]
Thanks a lot!
